---
# Workaround for strange handler variable visibility
- name: Saving config name for handler
  set_fact:
    openvpn_service_name: "{{ ovpn_login }}"
    openvpn_no_service: "{{ no_service }}"

- name: "{{ ovpn_login }}. Reading keys and certificates"
  set_fact:
    config_key: "{{ lookup('file', openvpn_pki_folder + '/pki/private/' + name + '.key' ) }}"
    config_crt: "{{ lookup('file', openvpn_pki_folder + '/pki/issued/' + name + '.crt' ) }}"
    ca_crt: "{{ lookup('file', openvpn_pki_folder + '/pki/ca.crt') }}"
    dh: "{{ lookup('file', openvpn_pki_folder + '/pki/dh.pem') }}"

- name: "{{ ovpn_login }}. Reading ta_key"
  set_fact:
    ta_key: "{{ lookup('file', openvpn_pki_folder + '/ta.key') }}"
  when: tls_auth

- debug:
    msg: "Config type is: {{ type }}"

- name: "{{ ovpn_login }}. Creating openvpn config"
  template:
    src: "{{ type }}_config.conf.j2"
    dest: "{{ config_path }}/{{ ovpn_login }}.conf"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: 0600
  notify: restart openvpn

- name: "{{ ovpn_login }}. Creating up script files"
  copy:
    dest: "{{ config_path }}/{{ ovpn_login }}-up.sh"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: 0700
    content: "{{up_script}}"
  when: up_script is defined
  notify: restart openvpn

- name: "{{ ovpn_login }}. Creating down script files"
  copy:
    dest: "{{ config_path }}/{{ ovpn_login }}-down.sh"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: 0700
    content: "{{down_script}}"
  when: down_script is defined
  notify: restart openvpn

- name: "{{ ovpn_login }}. Creating client-config directory for server config"
  block:
    - name: Creating folder
      file:
        path: "{{ config_path }}/{{ ovpn_login }}-ccd"
        state: directory
        owner: "{{ owner }}"
        group: "{{ group }}"
        mode: 0700

    - name: Creating client configs
      template:
        src: "ccd.j2"
        dest: "{{ config_path }}/{{ ovpn_login }}-ccd/{{ client.name }}"
        owner: "{{ owner }}"
        group: "{{ group }}"
        mode: 0600
      with_items: "{{ clients }}"
      loop_control:
        loop_var: client
      notify: restart openvpn
  when: type == "server" and clients is defined

- name: "{{ ovpn_login }}. Allow OpenVPN to listen on"
  seport:
    ports: "{{ se_port }}"
    proto: "{{ se_proto }}"
    setype: openvpn_port_t
    state: present
  when: se_port is defined and se_proto is defined
  notify:
    - restart openvpn

- meta: flush_handlers

- name: "{{ ovpn_login }}. Start OpenVPN"
  service:
    name: "openvpn@{{ ovpn_login }}"
    state: started
  when: not no_service

- name: "{{ ovpn_login }}. Enabling OpenVPN connection"
  command: "systemctl enable openvpn@{{ ovpn_login }}"
  changed_when: false
  when: not no_service
