---
- debug: 
    msg: "{{ easyrsa_install_dir }}"

- name: "Check easyrsa directory exists "
  stat:
    path: "{{ easyrsa_install_dir }}"
  register: is_easyrsa_exists 

- name: "Create easyrsa dir"
  file:
    path: "{{ easyrsa_install_dir }}"
    mode: 0700
    state: directory
  when: not is_easyrsa_exists.stat.exists or not is_easyrsa_exists.stat.isdir

  #- name: "Install modern 3.x easyrsa"
  #  become: yes
  #  get_url:
  #    url: "{{ easyrsa_download_url }}"
  #    dest: "{{ openvpn_pki_folder }}/easyrsa/{{ easyrsa_archivename }}"
  #  tags: [never, install]

- name: "Download and extract modern 3.x easyrsa"
  unarchive:
    remote_src: yes
    src: "{{ easyrsa_download_url }}"
    dest: "{{ easyrsa_install_dir }}"
    extra_opts:
      - "--strip-components"
      - "1"

- name: "Create symlink for the openssl-easyrsa.cnf file"
  file:
    src: "{{ easyrsa_install_dir }}/openssl-easyrsa.cnf"
    dest: "{{ openvpn_pki_folder }}/pki/openssl-easyrsa.cnf"
    state: link

- name: "Creating folders for OpenVPN PKI"
  file:
    path: "{{ openvpn_pki_folder }}/pki/{{ item }}/"
    state: directory
    mode: 0700
  with_items:
    - "revoked/certs_by_serial"
    - "revoked/private_by_serial"
    - "revoked/reqs_by_serial"
    - "renewed/certs_by_serial"
    - "renewed/private_by_serial"
    - "renewed/reqs_by_serial"
  delegate_to: localhost
  become: no
