---
- name: "{{ ovpn_login }}. Checking OpenVPN installed"
  package:
    name: openvpn
    state: present

- name: "Prepare manager's host"
  block:
    - name: "Check easyrsa directory exists "
      stat:
        path: "{{ _ovpn_config.easyrsa.install_dir }}"
      register: is_easyrsa_exists 
    
    - name: "Create easyrsa dir"
      file:
        path: "{{ _ovpn_config.easyrsa.install_dir }}"
        mode: 0700
        state: directory
      when: not is_easyrsa_exists.stat.exists or not is_easyrsa_exists.stat.isdir
    
    - name: "Download and extract modern 3.x easyrsa script"
      unarchive:
        remote_src: yes
        src: "{{ _ovpn_config.easyrsa.download_url }}"
        dest: "{{ _ovpn_config.easyrsa.install_dir }}"
        extra_opts:
          - "--strip-components"
          - "1"
    
    - name: "Create symlink for the openssl-easyrsa.cnf file"
      file:
        src: "{{ _ovpn_config.easyrsa.install_dir }}/openssl-easyrsa.cnf"
        dest: "{{ _ovpn_config.manager.pki_folder }}/pki/openssl-easyrsa.cnf"
        state: link
    
    - name: "Creating folders for OpenVPN PKI"
      file:
        path: "{{ _ovpn_config.manager.pki_folder }}/pki/{{ item }}/"
        state: directory
        mode: 0700
      with_items:
        - "revoked/certs_by_serial"
        - "revoked/private_by_serial"
        - "revoked/reqs_by_serial"
        - "renewed/certs_by_serial"
        - "renewed/private_by_serial"
        - "renewed/reqs_by_serial"

    - include_tasks: 'pki-config.yaml'

    - include_tasks: 'key-generate.yaml'
      vars:
        type:  'client'
        values: '{{ _ovpn_config.clientsof }}'
      when: _ovpn_config.clientsof is defined and _ovpn_config.clientsof != []
    - include_tasks: 'key-generate.yaml'
      vars:
        type:  'server'
        values: '{{ _ovpn_config.servers }}'
      when: _ovpn_config.servers is defined and _ovpn_config.servers != []

  delegate_to: "{{ _ovpn_config.manager.host }}"
  become: no
