---
- name: Add an Apt signing key for Docker CE repository
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture
  changed_when: False

- name: Adding docker apt repository
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: "deb [arch={{ deb_architecture.stdout }}] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
    backup: yes